-- Gỡ sạch bộ dữ liệu thật (và mọi thứ app đã tạo ra DỰA TRÊN nó: bài làm trên đề của
-- bộ dữ liệu, đề/câu hỏi do tài khoản tt-* soạn thêm...). Không đụng dữ liệu khác.
-- Thứ tự xoá theo khoá ngoại: bảng con trước, bảng cha sau.
DELETE FROM Notifications WHERE UserID LIKE 'tt-%';
DELETE FROM Bookmarks WHERE UserID LIKE 'tt-%' OR QuestionID IN (SELECT QuestionID FROM Questions WHERE BankID BETWEEN 20001 AND 29999);
DELETE FROM MistakeEntries WHERE UserID LIKE 'tt-%' OR QuestionID IN (SELECT QuestionID FROM Questions WHERE BankID BETWEEN 20001 AND 29999);
DELETE FROM UserCardStates WHERE UserID LIKE 'tt-%' OR (ItemType = 'VOCAB' AND ItemID BETWEEN 20001 AND 29999) OR (ItemType = 'KANJI' AND ItemID BETWEEN 20001 AND 29999);
DELETE FROM LessonCompletions WHERE UserID LIKE 'tt-%' OR LessonID IN (SELECT LessonID FROM CourseLessons WHERE CourseID BETWEEN 20001 AND 29999);
DELETE FROM CourseEnrollments WHERE UserID LIKE 'tt-%' OR CourseID BETWEEN 20001 AND 29999;
DELETE FROM SubmissionDetails WHERE SubmissionID IN (SELECT SubmissionID FROM ExamSubmissions WHERE StudentID LIKE 'tt-%' OR ExamID BETWEEN 20001 AND 29999 OR ExamID IN (SELECT ExamID FROM Exams WHERE CreatedBy LIKE 'tt-%'));
DELETE FROM SubmissionDetails WHERE QuestionID IN (SELECT QuestionID FROM Questions WHERE BankID BETWEEN 20001 AND 29999);
DELETE FROM ExamSubmissions WHERE StudentID LIKE 'tt-%' OR ExamID BETWEEN 20001 AND 29999 OR ExamID IN (SELECT ExamID FROM Exams WHERE CreatedBy LIKE 'tt-%');
DELETE FROM CourseLessons WHERE CourseID BETWEEN 20001 AND 29999 OR CourseID IN (SELECT CourseID FROM Courses WHERE AuthorID LIKE 'tt-%') OR ExamID BETWEEN 20001 AND 29999 OR DeckID BETWEEN 20001 AND 29999;
DELETE FROM Courses WHERE CourseID BETWEEN 20001 AND 29999 OR AuthorID LIKE 'tt-%';
DELETE FROM RoomMembers WHERE UserID LIKE 'tt-%' OR RoomID BETWEEN 20001 AND 29999 OR RoomID IN (SELECT RoomID FROM Rooms WHERE OwnerID LIKE 'tt-%');
DELETE FROM RoomExams WHERE RoomID BETWEEN 20001 AND 29999 OR ExamID BETWEEN 20001 AND 29999 OR RoomID IN (SELECT RoomID FROM Rooms WHERE OwnerID LIKE 'tt-%') OR ExamID IN (SELECT ExamID FROM Exams WHERE CreatedBy LIKE 'tt-%');
DELETE FROM Rooms WHERE RoomID BETWEEN 20001 AND 29999 OR OwnerID LIKE 'tt-%';
DELETE FROM ExamQuestionAnswers WHERE ExamID BETWEEN 20001 AND 29999 OR ExamID IN (SELECT ExamID FROM Exams WHERE CreatedBy LIKE 'tt-%') OR QuestionID IN (SELECT QuestionID FROM Questions WHERE BankID BETWEEN 20001 AND 29999);
DELETE FROM ExamQuestions WHERE ExamID BETWEEN 20001 AND 29999 OR ExamID IN (SELECT ExamID FROM Exams WHERE CreatedBy LIKE 'tt-%') OR QuestionID IN (SELECT QuestionID FROM Questions WHERE BankID BETWEEN 20001 AND 29999);
DELETE FROM ExamSections WHERE ExamID BETWEEN 20001 AND 29999;
DELETE FROM Exams WHERE ExamID BETWEEN 20001 AND 29999 OR CreatedBy LIKE 'tt-%';
DELETE FROM DeckItems WHERE DeckID BETWEEN 20001 AND 29999 OR ItemID BETWEEN 20001 AND 29999;
DELETE FROM Decks WHERE DeckID BETWEEN 20001 AND 29999 OR OwnerID LIKE 'tt-%';
DELETE FROM VocabItems WHERE VocabID BETWEEN 20001 AND 29999;
DELETE FROM KanjiItems WHERE KanjiID BETWEEN 20001 AND 29999;
DELETE FROM QuestionTags WHERE TagID BETWEEN 20001 AND 29999 OR QuestionID IN (SELECT QuestionID FROM Questions WHERE BankID BETWEEN 20001 AND 29999);
DELETE FROM Answers WHERE QuestionID IN (SELECT QuestionID FROM Questions WHERE BankID BETWEEN 20001 AND 29999 OR BankID IN (SELECT BankID FROM QuestionBanks WHERE TeacherID LIKE 'tt-%'));
DELETE FROM Questions WHERE BankID BETWEEN 20001 AND 29999 OR BankID IN (SELECT BankID FROM QuestionBanks WHERE TeacherID LIKE 'tt-%');
DELETE FROM ReadingPassages WHERE BankID BETWEEN 20001 AND 29999 OR BankID IN (SELECT BankID FROM QuestionBanks WHERE TeacherID LIKE 'tt-%');
DELETE FROM QuestionBanks WHERE BankID BETWEEN 20001 AND 29999 OR TeacherID LIKE 'tt-%';
DELETE FROM Tags WHERE TagID BETWEEN 20001 AND 29999;
DELETE FROM Users WHERE UserID LIKE 'tt-%';
